### ISSUE TITLE
Test the software 

### ISSUE THREAD

**Issue by OrsonMM** [dvav/dgeclust#1]
Hi team of dgeclust 

I tried to use the library using my data. But I have these error in the step 

$ mgr.new(data, mdl)

anaconda2/lib/python2.7/site-packages/dgeclust/stats.py:250: RuntimeWarning: divide by zero encountered in log
  lcp = np.log(1-v).cumsum()

What is your recommendation 
Please help.

**Comment by dvav** [comment]
Dear Orson,

Thank you for your feedback. I just published a release that hopefully fixes the problem.
Please, let me know whether this works for you. Thank you for your interest in DGEclust.

Best wishes,
Dimitris

**Comment by dvav** [comment]
Dear Orson,

Thank you for your feedback. I just published a release that hopefully fixes the problem.
Please, let me know whether this works for you. Thank you for your interest in DGEclust.

Best wishes,
Dimitris

**Comment by OrsonMM** [comment]
Hi Dimitris 
Thank you very much for your prompt response. It works well.
But now I have other problem. in other step 

$ res, nsamples = compare_groups(data, mdl, group1='4', group2='2')

Starting job # 0 in a separate thread.
/usr/local/lib/python2.7/dist-packages/dgeclust/postprocessing.py:63: RuntimeWarning: invalid value encountered in double_scalars
  post = np.sum(p, 0) / nsamples
Traceback (most recent call last):
  File "EcoDef2Met.py", line 66, in <module>
    main()
  File "EcoDef2Met.py", line 59, in main
    change(file2)
  File "EcoDef2Met.py", line 44, in change
    res, nsamples = compare_groups(data, mdl, group1='4', group2='2')
  File "/usr/local/lib/python2.7/dist-packages/dgeclust/postprocessing.py", line 66, in compare_groups
    tmp = post[ii].cumsum() / np.arange(1, post.size+1)
IndexError: invalid index to scalar variable.

Please help me again !!

**Comment by dvav** [comment]
Hi Orson,

Just to clarify: before you call the compare_groups function, do you wait until the simulation has finished? You must have observed that when you call mgr.new(data, mdl), the simulation starts running in the background. You can periodically check its progress by using the plot_progress method of the mdl object. If you call compare_groups before the simulation has actually finished, you 'll get an error.

If the above does not solve your problem, could you please send to me the relevant code chunk to get an idea about how exactly you use the software?

Many thanks...

**Comment by dvav** [comment]
Hi Orson,

Just to clarify: before you call the compare_groups function, do you wait until the simulation has finished? You must have observed that when you call mgr.new(data, mdl), the simulation starts running in the background. You can periodically check its progress by using the plot_progress method of the mdl object. If you call compare_groups before the simulation has actually finished, you 'll get an error.

If the above does not solve your problem, could you please send to me the relevant code chunk to get an idea about how exactly you use the software?

Many thanks…

**Comment by OrsonMM** [comment]
Hi Dimitris
Thank´s for your recommendation, it works very well. 
Best wishes,
Orson

**Comment by dvav** [comment]
Glad to hear that. I will now close this issue. Good luck with your research.
