### ISSUE TITLE
Question about dendrogram

### ISSUE THREAD

**Issue by OrsonMM** [dvav/dgeclust#2]
Hi Dimitris

I have a question, what data is necessary for  do a dendogram with more than two groups. 

I think that I need the distance simvec and the res.FDR

Thank+s

**Comment by dvav** [comment]
Hi Orson,

I provide details on how to create a dendrogram [here](http://dvav.me/dgeclust/docs/tutorial/clust/). Since the dendrogram is over groups, the `compare_genes` parameter in function `compute_similarity_vector`  should be set to `False`. 

Hope this helps,
Dimitris

**Comment by dvav** [comment]
Hi Orson, 

Did you sort this out? Please, let me know, so that I can close this issue.

Best wishes,
Dimitris
